apiVersion: v1
kind: Service
metadata:
  labels:
    app: docker-waf
  name: docker-waf
spec:
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: 80
  selector:
    app: docker-waf
    