apiVersion: v1
kind: Service
metadata:
  labels:
    app: docker-clamav
  name: docker-clamav
spec:
  ports:
  - name: socket
    port: 3310
    protocol: TCP
    targetPort: 3310
  selector:
    app: docker-clamav
    