apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: clamav-data
  labels:
    app: clamav
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: openebs-cstor
