apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: docker-clamav
  name: docker-clamav
spec:
  replicas: 1
  selector:
    matchLabels:
      app: docker-clamav
  template:
    metadata:
      labels:
        app: docker-clamav
    spec:
      containers:
      - image: mkodockx/docker-clamav:1.0.4-alpine
        imagePullPolicy: Always
        name: docker-clamav
        volumeMounts:
        - mountPath: /var/atlassian/application-data/jira
          name: clamav-data
      volumes:
      - name: clamav-data
        persistentVolumeClaim:
          claimName: clamav-data
