apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: docker-clamav
  name: docker-clamav
spec:
  replicas: 1
  selector:
    matchLabels:
      app: docker-clamav
  template:
    metadata:
      labels:
        app: docker-clamav
    spec:
      securityContext:
        runAsUser: 100
        runAsGroup: 101
        fsGroup: 101    
      containers:
      - image: mkodockx/docker-clamav:1.1.2-alpine
        imagePullPolicy: Always
        name: docker-clamav
        volumeMounts:
        - mountPath: /var/lib/clamav
          name: clamav-data
      volumes:
      - name: clamav-data
        persistentVolumeClaim:
          claimName: clamav-data
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: clamav-data
  labels:
    app: clamav
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: $STORAGECLASS
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: docker-clamav
  name: docker-clamav
spec:
  ports:
  - name: socket
    port: 3310
    protocol: TCP
    targetPort: 3310
  selector:
    app: docker-clamav
    
